### ISSUE TITLE
Common binary data reading example or gallary?

### ISSUE THREAD

**Issue by WindSoilder** [sharksforarms/deku#275] opened 2022-07-15 01:34 UTC
I think it's good to have some examples like how to define common binary format, like https://formats.kaitai.io/

**Comment by sharksforarms** [comment] 2022-07-16 19:14
Hi @WindSoilder , examples are a great way of learning a library and it's features and more examples could not hurt.

There are some examples here: https://github.com/sharksforarms/deku/tree/master/examples

Feel free to contribute some more!

Closing for now as duplicate of:
https://github.com/sharksforarms/deku/issues/18

**Closed by sharksforarms** 2022-07-16 19:14 UTC
